on:
  pull_request:
    branches:
      - master
    types: [closed]


name: deploy
jobs:
  build-and-push:
    if: ${{ github.event.pull_request.merged }}
    name: build and push image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build and push to docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_USERNAME }}/test-gha
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
